# docker-compose.yml

version: '3.8'

services:
  weather-app:
    build: .
    ports:
      - "5000:5000"   # API service
      - "8080:8080"   # UI service
    environment:
      - DEBUG=True
      - SECRET_KEY=supersecretkey
      - TWILIO_ACCOUNT_SID=your_account_sid_here
      - TWILIO_AUTH_TOKEN=your_auth_token_here
      - TWILIO_PHONE_NUMBER=+1234567890
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: weather_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
